project:
  type: website
  output-dir: _site
  execute-dir: project
  render:
    - index.qmd
    - 01_data_wrangling.qmd
    - 02_effect_size_lnRR.qmd
    - 03_dependency_structure_audit.qmd
    - 04_overall_effect.qmd
    - 05_uni_moderators.qmd
    - 06_publication_bias.qmd
    - 07_crime_q.qmd

website:
  title: "Prenatal chronic noise exposure meta-analysis"
  page-navigation: true
  sidebar:
    style: docked
    search: true
    contents:
      - text: "Online supplementary"
        href: index.qmd
      - text: "Data preparation"
        href: 01_data_wrangling.qmd
      - text: "Effect size calculation"
        href: 02_effect_size_lnRR.qmd
      - text: "Sampling variance-covariance matrix"
        href: 03_dependency_structure_audit.qmd
      - text: "Overall effect"
        href: 04_overall_effect.qmd
      - text: "Uni-moderators"
        href: 05_uni_moderators.qmd
      - text: "Publication bias"
        href: 06_publication_bias.qmd
      - text: "CRIME-Q appraisal"
        href: 07_crime_q.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - styles.scss
    toc: true
    toc-location: left
    code-fold: false
    code-tools: true
    code-copy: true
    number-sections: false
    page-layout: full
    smooth-scroll: true

execute:
  echo: true
  warning: false
  message: false
  freeze: auto
