project:
  type: book
  output-dir: _site
  execute-dir: project

book:
  title: "Prenatal Chronic Noise Exposure Meta-analysis"
  author: "Anna Lenz"
  chapters:
    - index.qmd
    - 01_data_wrangling.qmd
    - 02_effect_size_lnRR.qmd
    - 03_overall_effect.qmd
    - 04_uni_moderators.qmd
    - 05_publication_bias.qmd
    - 06_crime_q.qmd
    - 07_leave_one_out.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
    code-fold: false
    code-tools: true
    number-sections: true

execute:
  echo: true
  warning: true
  message: false
  freeze: auto
